"""Investment pitch UI tab.

Renders the AI-generated investment pitch and offers a PDF download.
"""
from __future__ import annotations

import io
import logging
from datetime import datetime
from typing import Optional

import streamlit as st

from analysis.pitch import PitchResult

logger = logging.getLogger(__name__)


# ── PDF generation ─────────────────────────────────────────────────────────────

def _build_pdf(pitch: PitchResult, ticker: str, current_price: float) -> bytes:
    """Generate a simple PDF of the pitch using reportlab."""
    from reportlab.lib import colors
    from reportlab.lib.pagesizes import letter
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        HRFlowable, Paragraph, SimpleDocTemplate, Spacer
    )

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        leftMargin=1 * inch,
        rightMargin=1 * inch,
        topMargin=1 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "PitchTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#1976D2"),
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        "PitchSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        spaceAfter=12,
    )
    section_style = ParagraphStyle(
        "PitchSection",
        parent=styles["Heading2"],
        fontSize=12,
        textColor=colors.HexColor("#1a1a1a"),
        spaceBefore=14,
        spaceAfter=4,
    )
    body_style = ParagraphStyle(
        "PitchBody",
        parent=styles["Normal"],
        fontSize=10,
        leading=15,
        spaceAfter=6,
    )
    bullet_style = ParagraphStyle(
        "PitchBullet",
        parent=styles["Normal"],
        fontSize=10,
        leading=14,
        leftIndent=14,
        spaceAfter=3,
    )
    footer_style = ParagraphStyle(
        "PitchFooter",
        parent=styles["Normal"],
        fontSize=7,
        textColor=colors.HexColor("#888888"),
        spaceBefore=10,
    )

    story = []

    # Header
    story.append(Paragraph(f"{ticker} — Investment Pitch", title_style))
    story.append(Paragraph(
        f"{pitch.company_name} &nbsp;|&nbsp; "
        f"Current Price: ${current_price:.2f} &nbsp;|&nbsp; "
        f"Generated: {pitch.generated_at.strftime('%Y-%m-%d %H:%M UTC')}",
        subtitle_style,
    ))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1976D2")))
    story.append(Spacer(1, 8))

    # Helper to render a section
    def add_section(title: str, text: str, bullets: list[str] | None = None) -> None:
        if not text and not bullets:
            return
        story.append(Paragraph(title, section_style))
        if text:
            # Escape & for XML safety
            safe = text.replace("&", "&amp;").replace("<", "&lt;")
            story.append(Paragraph(safe, body_style))
        if bullets:
            for b in bullets:
                safe_b = b.replace("&", "&amp;").replace("<", "&lt;")
                story.append(Paragraph(f"• {safe_b}", bullet_style))

    # Sections — use raw pitch_text if structured parsing failed
    if pitch.company_overview:
        add_section("Company Overview", pitch.company_overview)
    if pitch.investment_thesis:
        add_section("Investment Thesis", "", pitch.investment_thesis)
    if pitch.key_catalysts:
        add_section("Key Catalysts", "", pitch.key_catalysts)
    if pitch.risks:
        add_section("Risks", "", pitch.risks)
    if pitch.valuation_perspective:
        add_section("Valuation Perspective", pitch.valuation_perspective)
    if pitch.conclusion:
        add_section("Conclusion", pitch.conclusion)

    # If parsing failed, dump the full text
    if not any([pitch.company_overview, pitch.investment_thesis, pitch.risks]):
        story.append(Paragraph("Full Pitch", section_style))
        safe_full = pitch.pitch_text.replace("&", "&amp;").replace("<", "&lt;").replace(
            "\n", "<br/>"
        )
        story.append(Paragraph(safe_full, body_style))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(Paragraph(
        "DISCLAIMER: This pitch was generated by an AI model and is for informational purposes only. "
        "It does not constitute investment advice, a recommendation to buy or sell any security, "
        "or a solicitation of any transaction. All outputs are model-derived and subject to error.",
        footer_style,
    ))

    doc.build(story)
    buf.seek(0)
    return buf.read()


# ── Main render ────────────────────────────────────────────────────────────────

def render_pitch(
    pitch: Optional[PitchResult],
    ticker: str,
    current_price: float,
    is_loading: bool = False,
    error_msg: str = "",
) -> None:
    """Render the pitch tab contents.

    Caller is responsible for triggering pitch generation; this function only renders.
    """
    if is_loading:
        st.info("Generating investment pitch with Claude AI...")
        with st.spinner("Streaming from Claude..."):
            st.empty()
        return

    if error_msg:
        st.error(error_msg)
        return

    if pitch is None:
        st.info("Click **Generate Pitch** to create an AI-powered investment pitch for this ticker.")
        return

    # ── Top meta row ──────────────────────────────────────────────────────────
    col_a, col_b, col_c = st.columns([2, 2, 1])
    col_a.caption(f"**{pitch.company_name}** ({ticker})")
    if pitch.token_usage:
        col_b.caption(f"Model: {pitch.model_used} | "
                      f"Tokens: {pitch.token_usage.get('input_tokens', '?')} in / "
                      f"{pitch.token_usage.get('output_tokens', '?')} out")
    else:
        col_b.caption(f"Mode: {pitch.model_used}")
    col_c.caption(f"Generated: {pitch.generated_at.strftime('%Y-%m-%d %H:%M')}")

    st.divider()

    # ── Render each section ───────────────────────────────────────────────────
    if pitch.company_overview:
        st.subheader("Company Overview")
        st.write(pitch.company_overview)

    if pitch.investment_thesis:
        st.subheader("Investment Thesis")
        for item in pitch.investment_thesis:
            st.markdown(f"- {item}")

    if pitch.key_catalysts:
        st.subheader("Key Catalysts")
        for cat in pitch.key_catalysts:
            st.markdown(f"- {cat}")

    if pitch.risks:
        st.subheader("Risks")
        for risk in pitch.risks:
            st.markdown(f"- {risk}")

    if pitch.valuation_perspective:
        st.subheader("Valuation Perspective")
        st.write(pitch.valuation_perspective)

    if pitch.conclusion:
        st.subheader("Conclusion")
        st.info(pitch.conclusion)

    # Fallback: render raw markdown
    if not any([pitch.company_overview, pitch.investment_thesis,
                pitch.risks, pitch.valuation_perspective]):
        st.markdown(pitch.pitch_text)

    st.divider()

    # ── PDF export ────────────────────────────────────────────────────────────
    col_pdf, _ = st.columns([1, 3])
    with col_pdf:
        try:
            pdf_bytes = _build_pdf(pitch, ticker, current_price)
            filename = f"{ticker}_pitch_{pitch.generated_at.strftime('%Y%m%d')}.pdf"
            st.download_button(
                label="Download PDF",
                data=pdf_bytes,
                file_name=filename,
                mime="application/pdf",
                type="secondary",
            )
        except Exception as exc:
            logger.warning("PDF generation failed: %s", exc)
            st.caption(f"PDF export unavailable: {exc}")

    # ── Disclaimer ────────────────────────────────────────────────────────────
    st.caption(
        "**Disclaimer:** This pitch was generated by an AI language model using model-derived "
        "quantitative data. It is for informational purposes only and does not constitute "
        "investment advice or a recommendation to buy or sell any security."
    )
